version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - ./docker/mongodb/database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: wishlist

  wishlist-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongodb:27017/wishlist?authSource=admin
    depends_on:
      - mongodb
    restart: always
